### ISSUE TITLE
Upgrade to 2.2.7 breaks backwards compatibility due to the file name change

### ISSUE THREAD

**Issue by moizr** [darul75/angular-awesome-slider#100]
Based on semver rules shouldn't the version have been set to 2.3 since the file name changed? We are bower users and we had a dependency on ng-slider.min.js. We had set the version in bower to ~2.2.2 and that downloaded 2.2.7 during our build and our packaging script failed to package ng-slider*.js because it's file name had changed.

**Comment by darul75** [comment]
yes my mistake, I will delete 2.2.7 it and put a new release 2.3

**Comment by darul75** [comment]
I have deleted previous 2.2,7 tag and created a 2.3.0 one, is it better for your build, sorry for filename changes...I knew it will be bad for everyone but so many people asked me to change the name, it had to be done :)
