### ISSUE TITLE
Usage with bootstrap forms?

### ISSUE THREAD

**Issue by jsinai** [darul75/angular-awesome-slider#105]
Hi, I'd like to drop your slider into my bootstrap form. Currently the font size doesn't match, and the spacing doesn't look good. It would really help if I change the font size, for example?

**Comment by darul75** [comment]
Hi,
You can add your own css class name with className option.
Then just add a rule for both  div.jslider-label and div.jslider-value.
Tell me if it is fine

**Comment by jsinai** [comment]
That worked, thanks! For the benefit of other users, here's what I did:

In my controller:

    $scope.options = {
        className: 'myslider'
    };

In my CSS:

.myslider div.jslider-label {
    font-size: 12px;
}

.myslider div.jslider-value {
    font-size: 12px;
}


Julian

**Comment by darul75** [comment]
thx for sharing

**Comment by darul75** [comment]
do not hesitate put a star in the sky ;)
