### ISSUE TITLE
ng-Slider not supported for FLOAT values (in step attr)

### ISSUE THREAD

**Issue by gopisf** [darul75/angular-awesome-slider#108]
In slider, step value is in float ( step : 0.5 ) is not working. Is there any other way to use float values in ng-slider??

**Comment by darul75** [comment]
Hi, I do not remember that case and need to check code

**Comment by gopisf** [comment]
Thank u @darul75. Please add that feature or give a suggestion.

**Comment by darul75** [comment]
try by adding this option attribute, 
```
{
 "round": 1,
 "step": 0.5
}
```

**Comment by gopisf** [comment]
Thank u Darul. Its working now.
