### ISSUE TITLE
Trouble setting up

### ISSUE THREAD

**Issue by slikk66** [darul75/angular-awesome-slider#111]
The README says use:

```
<link rel="stylesheet" type="text/css" href="angular-awesome-slider.min.css">
<script type="text/javascript" src="angular-awesome-slider.min.js"></script>
angular.module('myApp', ['angularAwesomeSlider']);
```

But when I do that, it doesn't work.. I just get a text box where the slider should be.  If you click on the examples: http://darul75.github.io/angular-awesome-slider/

It shows:

```
  <link href="css/ng-slider.min.css" rel="stylesheet" />
  <script type="javascripts/javascript" src="angular.min.js" />
  <script type="javascripts/javascript" src="ng-slider.min.js" />
```

If you download the ZIP, "ng-slider" isn't in there..

What gives?

I've gotten it to work sort of by going to some plunks and looking at the source, but they all use ngSlider, none of them use "awesome" anything to get the slider working..  what am I missing?

**Comment by darul75** [comment]
Hi,
Sorry but I had to rename the module because of ng prefix reserved for angular components.
And demo page is not refactored.
Have a look there 

https://github.com/darul75/angular-awesome-slider/blob/master/src/index.html

**Comment by darul75** [comment]
Then it depends which version you want to use. New ones use angular-awesome name.

**Comment by darul75** [comment]
did it work ?

**Comment by slikk66** [comment]
Yes, I got it working.. thank you for the help!
