### ISSUE TITLE
Slider  reset not working as expected

### ISSUE THREAD

**Issue by praswebdev** [darul75/angular-awesome-slider#113]
Hi,
I am using a slider with two pointers. when you move the slider pointers to left most and click on reset button, the slider is not resetting properly.
for example,

in the fiddle below,
on load i set the age to 34 and 67, and then u move the left pointer to 53 and the click reset, the pointer movers to default age 34.

Then move the left pointer to 26 and the right one to 29 and then click on rest button, left pointer is not resetting to default age 34.

I am using version 2.2.2, and unfortunately at this point cannot upgrade. 

http://jsfiddle.net/dmohan/hkp72ftL/10/

**Comment by darul75** [comment]
hi I have seen it, I try to ckeck it tonight, sorry for delay

**Comment by praswebdev** [comment]
Thanks a lot. Could you please let me know the fix for it too. So I can put in version 2.2.2. At this point of my project I cannot upgrade to latest .

**Comment by darul75** [comment]
I have reproduced, so I gonna check with new version to see if it has been solved and replace 2.2.2 tag with this fix.

**Comment by darul75** [comment]
hi a fix is available here,

https://github.com/darul75/angular-awesome-slider/releases/tag/2.2.6-patch

you can check here 

http://jsfiddle.net/darul75/q0ong5ot/

it includes all fix or enhancement to 2.2.6 but it does not change directive name, still ng-slider

2.2.6: refactoring classnames
2.2.5: skin availables + less all css
2.2.4: fix when 2 pointers overlap on limits
2.2.3: mouse up event indicator in callback

**Comment by praswebdev** [comment]
Thanks a lot. but do u mind patching it in 2.2.2. I have some custom template changes and some fix for IE8 too

**Comment by praswebdev** [comment]
Thanks a lot. I will test and let you know

**Comment by darul75** [comment]
main change is from $watch for options object made with equality and not reference..so it was not triggering change event.

https://github.com/darul75/angular-awesome-slider/blob/patch/src/core/ng-slider.js#L133

can you then give me some tips to make slider working under ie8, someone (I realize it you ;) ) was asking for it here https://github.com/darul75/angular-awesome-slider/issues/56

**Comment by praswebdev** [comment]
Hi tested it. but could find label and pointer overlapping after reset is clicked

**Comment by praswebdev** [comment]
For IE8 I have made the following fix

1.    replaced pageX and pageY with clientX and clientY, as these were not defined in    IE8            
 ex:   x:  a.pageX || a.clientX,
         y:  a.pageY || a.clientY

2. Same with textContent , if not defined changed to innerText

**Comment by praswebdev** [comment]
Hi
Looks like the threshold is not setting properly on reset.Could you please take a look at this issue?

**Comment by darul75** [comment]
yes it is fixed on same release, I have erased previous one so you can give a try and dowload it. but code needs to be refactored...so dirty there sometimes, I will do it in current release not for previous

**Comment by praswebdev** [comment]
you mean it is fixed for version 2.2.2?
Also we have the label overlap issue after reset clicked  in 2.2.6 patch too? was that too fixed?

**Comment by darul75** [comment]
Well I have to move what I have done inn patch for a 2.2.2 version forget the 2.2.6 fix..too much thing at same time here. I try to create a patch tomorrow  :)

**Comment by praswebdev** [comment]
I verified this is in 2.2.6 patch and looks fixed. I shall do some more testing. Let me try to pull those changes in 2.2.2 and see if i can fix this. Thanks a lot for fixing this one.
Unfortunately we have a dependency with the templates and styles, so i cannot easily upgrade to higher versions.

**Comment by darul75** [comment]
No problem, it just take me a while to maintain it and go into code, long time ago it exists now ;) i check too what ican do to help you

**Comment by darul75** [comment]
can you check this one : https://github.com/darul75/angular-awesome-slider/releases/tag/2.2.2-patch

**Comment by darul75** [comment]
thx for IE info

**Comment by praswebdev** [comment]
thanks a lot. it worked :-)
