### ISSUE TITLE
heterogeneity setting is not working

### ISSUE THREAD

**Issue by mihaipanait** [darul75/angular-awesome-slider#117]
scope.options = {               
from: 0,
to: 40,
step: 0.5,
dimension: " $",
round: 1,
scale: [0, '|', 50, '|', 400],
heterogeneity: ['50/100', '75/250']
};

heterogeneity setting is not working as it does in the base jquery plugin.

**Comment by darul75** [comment]
ok, let me check, this part has been changed by some and me...:)

**Comment by darul75** [comment]
you can updgrade to https://github.com/darul75/angular-awesome-slider/releases/tag/2.3.7

**Comment by mihaipanait** [comment]
Great
Thank you!
