### ISSUE TITLE
Reinitialize slider with diff set of options

### ISSUE THREAD

**Issue by venkata82** [darul75/angular-awesome-slider#120]
I have an angular app. I'm using slider for music app. when a song changes, I like to reinitialize slider. But, does not find an option.

**Comment by darul75** [comment]
are you changing options attribute dynamically ?

**Comment by venkata82** [comment]
Yes. I change attributes dynamically. 

Sent from Yahoo Mail on Android

**Comment by darul75** [comment]
made some tests with small changes and slider rebuild automatically.

```javascript
      scope.changeOptions = function() {

        scope.options.from = 20;
        scope.options.to = 50;
...

   }
```

any code to share with me

**Comment by venkata82** [comment]
The problem is actually with the Angular Scope. I integrated awesome slider as a HTML5 Audio control skin. I lost $scope digestion on HTML5 Audio control events. I had to apply scope manually to fix issue. Thanks for your quick response. Appreciated!

**Comment by darul75** [comment]
Good news scope sharing is quite difficult sometimes in angular. But I will check my mobile events again and refactore when got time :)
