### ISSUE TITLE
On using "threshold" in the options in slider with two pointers the callback is not fired in case slider is on threshold values.

### ISSUE THREAD

**Issue by mechanicals** [darul75/angular-awesome-slider#121]
Here is fiddle: 

http://jsfiddle.net/g9e9n8xc/314/

Check for "$scope.options2"  in the fiddle. Have added a threshold of "5".
The callback is not fired when the range reaches the threshold value. 
For all other cases works fine.

**Comment by darul75** [comment]
reproduced, we ll check

**Comment by darul75** [comment]
wish you can use last version and not 'ng-slider' directiv old one..

fix in this current release : 

https://github.com/darul75/angular-awesome-slider/releases/tag/2.3.9

**Comment by mechanicals** [comment]
Thanks for the quick reply ad fix. Works perfectly now.
& Yes, I am using the latest version only.

**Comment by darul75** [comment]
good news, thx for feedback, I appreciate
