### ISSUE TITLE
associated ng-model is not updated as we drag the range

### ISSUE THREAD

**Issue by pliablepixels** [darul75/angular-awesome-slider#125]
Hi, I am using the following code in my slider:
```
<div style="width:90%">
    <input ng-model="ionRange.index" type="text" id="mySlider1" slider options="slider_options" realtime:true />
</div>
```

The problem I am facing is "ionRange.index" (ng-model) value is not being updated as I slide the slider. It only gets updated after I finish sliding. How do I make sure ng-model gets updated in real time?

thx

**Comment by darul75** [comment]
Hi, just put 'realtime' option attribute to true

**Comment by darul75** [comment]
You slider_options must be an json object as:

{from:...,to,....,realtime:true}

**Comment by pliablepixels** [comment]
ah perfect. Thank you. I had put the realtime into the html!

**Comment by darul75** [comment]
yes no pb, nice if it works fine
