### ISSUE TITLE
Callback for mouseup event or support for ngMouseup

### ISSUE THREAD

**Issue by tylerchamberland** [darul75/angular-awesome-slider#131]
I'm adding analytics to a widget using this slider.  I would like to fire an event when the user chooses a value on the slider, I initially tried to implement this using the callback option 

    {
        callback: function () {
          AnalyticsLogger.log(analyticsEvents.adjustAmount, scope);
        }
    }

but it fires every single time the value of the slider change and floods my analytics.  It would be nice to be able to set a callback that only fires when they've chosen a value.

**Comment by darul75** [comment]
Hi,
Can you give a try to put the following callback signature:

callback: function(value, released) {
    
    // released it triggered when mouse up
    console.log(value + " " + released);
}

**Comment by tylerchamberland** [comment]
oh wow, I'm a dolt; this is perfect thanks!

**Comment by darul75** [comment]
no that is really fine ;) nice if it works like a charm
