### ISSUE TITLE
programmatic control of "to" end value parameter?

### ISSUE THREAD

**Issue by jbana** [darul75/angular-awesome-slider#133]
hi,
is it possible to dynamically change the "to" parameter from code?  so either the slider would automatically recompute the grab positions or the developer would call some function to do so.
thanks

**Comment by darul75** [comment]
have you tried to just update your scope options 'to' attribute from your code

```javascript
$scope.options.to = 12; // your value
```

**Comment by jbana** [comment]
amazingly i hadnt tried that, works fine, thank you!

**Comment by darul75** [comment]
good dude
