### ISSUE TITLE
How to get current value in template ? 

### ISSUE THREAD

**Issue by flug** [darul75/angular-awesome-slider#137]
I am trying to overload the template to fit the design and I try to find the slider value ?

**Comment by darul75** [comment]
the slider value(s) ("to" for slider with 2 pointers) is contained there but as it also contains the dimension string label (km, meters) you choosed
https://github.com/darul75/angular-awesome-slider/blob/master/src/core/template/slider.tmpl.js#L22

here for pointers
https://github.com/darul75/angular-awesome-slider/blob/master/src/core/template/slider.tmpl.js#L18

**Comment by flug** [comment]
hum ok Thx :+1:
