### ISSUE TITLE
Dynamic switch from one handle to two and back.

### ISSUE THREAD

**Issue by hoopes** [darul75/angular-awesome-slider#140]
Hi, 

I was trying to find a slider that let me switch from range (two handles) to a slider with one handle, and the opposite value "pinned" to either max or min. The results (in words) I want to give are:
"values between x and y"
"values greater than x"
"values less than y"

I was trying to switch back and forth between "types" of values (numeric, and a string with a semicolon), and seemed like I got some undefined behavior.

http://jsfiddle.net/z5ep3n8c/1/

Is there a way to set the lower value to -Infinity, and the max to Infinity? If not, no problem at all.

Thanks very much for the directive, it looks really nice!

**Comment by darul75** [comment]
hi @hoopes,
nice catch, I have to make few tests to figure out how to resolve it but I am quite busy this time. 
I keep you in touch

**Comment by darul75** [comment]
Hi,

Current solution is to broadcast event when changing your value this way, sorry it can not be done in one time

// change model
$scope.value = '10;50';
// broadcast
$scope.$broadcast('slider-value-update', {value: '10;50'});


// change model
$scope.value = '10';
// broadcast
$scope.$broadcast('slider-value-update', {value: '10'});

use string for value :)

thx
