### ISSUE TITLE
0 is not accepted in custom labels for scale

### ISSUE THREAD

**Issue by lbayerl** [darul75/angular-awesome-slider#141]
try options.scale: [{val: 0, label:'low'}, {val:50, label:'medium'}] and you will notice that 0 is not an accepted val even if from 0 to 100 (e.g.) resulting in 'object'.
Wanted to create a fiddle but obviously the fiddle version itself seems outdated.

**Comment by darul75** [comment]
reproduced

**Comment by lbayerl** [comment]
Thanks for reacting so quickly!
