### ISSUE TITLE
Slider not showing decimal values

### ISSUE THREAD

**Issue by gauravjhs** [darul75/angular-awesome-slider#79]
If "step" is in decimal then slider should show decimal values.

**Comment by darul75** [comment]
just add round parameter in your options, by instance round:2

**Comment by joseAyudarte91** [comment]
It does not show decimals when set "from" and "to" properties. "round" property has no effect for me. Could it be related to a lower version of Angular? I use 1.2.14. Thanks.

**Comment by darul75** [comment]
can you send your options, I know I had many pb with decimal values...

**Comment by joseAyudarte91** [comment]
This is the jsfiddle with your last version (it seems 2.2.7, but the release's name is 2.3.0). I didn't change the css, but I have had some problems with it too.

https://jsfiddle.net/g9e9n8xc/176/

**Comment by darul75** [comment]
yes indeed...from and to in decimal cause issue. I have to check but do not remember how it works right now. Quite busy I will check when I can, thanks for feedback.

https://github.com/darul75/angular-awesome-slider/blob/master/src/core/model/slider.factory.js

I would like take a look right now but can not until few days.

**Comment by joseAyudarte91** [comment]
Ok, I will try to help you if I see something that could cause the issue. May be I can use a previous release at the moment. Nice work with this plugin. Thanks!

**Comment by darul75** [comment]
from and 2 were parse as integer values...

**Comment by joseAyudarte91** [comment]
Nice! I reviewed your code but I didn't have time to check it properly. Many thanks for your time! Cheers.

**Comment by darul75** [comment]
you are welcome, do not forget putting stars in the sky ;)
