### ISSUE TITLE
Updating value from code

### ISSUE THREAD

**Issue by funnygerman** [darul75/angular-awesome-slider#96]
I use your widget ng-slider. And I try to change the values (I use range values) and options also from the code depending on some user actions.

It seems that options will be refreshed, because I see everytime new bounds. But the value (the range) remains the same.

That is my code snippet:

    $scope.displaySliderRangeFilter = function(property) {
        var range = diagramProcessor.getNumericMetrics();
        $scope.slvalue = range[property].min+";"+range[property].max;
        $scope.sloptions = {
            from: range[property].min,
            to: range[property].max,
            step: 1,
            dimension: ""
        };
    };

**Comment by funnygerman** [comment]
I guess, this is the jsfiddle
http://jsfiddle.net/g9e9n8xc/143/

**Comment by darul75** [comment]
are you using "realtime" option, if not ok.
can you invert changing options first then value and tell me if it is still wrong.

    $scope.sloptions = {
        from: range[property].min,
        to: range[property].max,
        step: 1,
        dimension: ""
    };
 $scope.slvalue = range[property].min+";"+range[property].max;

http://jsfiddle.net/z4eugwo7/1/

**Comment by funnygerman** [comment]
If you didn't change slider values manually, then the button works only once. 
Otherwise the suggested solution doesn't work. Or better to say suggested solution doesn't work.
You can also see this problem in the your jsfiddle link you sent.

**Comment by samdanishaik** [comment]
I am trying something similar and facing the same issue. Is it fixed for you now?

**Comment by samdanishaik** [comment]
For me the button works multiple times until I change the value using slider. Once I change the value using slider everything is screwed. Please help me.

**Comment by darul75** [comment]
Sure guys there is a bug, on big holidays I have to fix it when back. Sorry for delay in responses.

**Comment by samdanishaik** [comment]
Hi Julien,

Sorry to bother you again. Can you please give a timeline for this fix. My app is currently dependent on these fixes.

Regards,
Samdani Shaik.

**Comment by darul75** [comment]
I might have time to look on sunday night ;) hope I will find where is issue

**Comment by samdanishaik** [comment]
That sounds good.

Thanks Julien.

**Comment by darul75** [comment]
hi @funnygerman,

problem is not about directive but how we use scope here, and is a common mistake we often make with string that are immutable and how scope uses javascript prototypal inheritance

just replace:

```js
$scope.slvalue = "1;100";
```

by

```js
$scope.slvalue = {
 value:"1;100"
};
```

```html
// later in directive template
<input ng-model="slvalue.value"  type="text" id="mySlider1" slider options="sloptions" /></div>',
```
and it will work fine

and you will it works better ;)

http://jsfiddle.net/whmuvyjd/

**Comment by samdanishaik** [comment]
That's great finding Julien.. Thanks for fixing it. It works awesome!!

**Comment by funnygerman** [comment]
Thank you, also worked for us

**Comment by darul75** [comment]
cool
